<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Municipios;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Municipios::create(['codMunicipio' => '01-01', 'nombreMunicipio' => 'Ahuachapán', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-02', 'nombreMunicipio' => 'Apaneca', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-03', 'nombreMunicipio' => 'Atiquizaya', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-04', 'nombreMunicipio' => 'Concepción de Ataco', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-05', 'nombreMunicipio' => 'El Refugio', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-06', 'nombreMunicipio' => 'Guaymango', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-07', 'nombreMunicipio' => 'Jujutla', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-08', 'nombreMunicipio' => 'San Francisco Menéndez', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-09', 'nombreMunicipio' => 'San Lorenzo', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-10', 'nombreMunicipio' => 'San Pedro Puxtla', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-11', 'nombreMunicipio' => 'Tacuba', 'codDepartamento' => '01']);
        Municipios::create(['codMunicipio' => '01-12', 'nombreMunicipio' => 'Turín', 'codDepartamento' => '01']);

        Municipios::create(['codMunicipio' => '02-01', 'nombreMunicipio' => 'Sensuntepeque', 'codDepartamento' => '02']);
        Municipios::create(['codMunicipio' => '02-02', 'nombreMunicipio' => 'Cinquera', 'codDepartamento' => '02']);
        Municipios::create(['codMunicipio' => '02-03', 'nombreMunicipio' => 'Dolores', 'codDepartamento' => '02']);
        Municipios::create(['codMunicipio' => '02-04', 'nombreMunicipio' => 'Guacotecti', 'codDepartamento' => '02']);
        Municipios::create(['codMunicipio' => '02-05', 'nombreMunicipio' => 'Ilobasco', 'codDepartamento' => '02']);
        Municipios::create(['codMunicipio' => '02-06', 'nombreMunicipio' => 'Jutiapa', 'codDepartamento' => '02']);
        Municipios::create(['codMunicipio' => '02-07', 'nombreMunicipio' => 'San Isidro', 'codDepartamento' => '02']);
        Municipios::create(['codMunicipio' => '02-08', 'nombreMunicipio' => 'Tejutepeque', 'codDepartamento' => '02']);
        Municipios::create(['codMunicipio' => '02-09', 'nombreMunicipio' => 'Victoria', 'codDepartamento' => '02']);

        Municipios::create(['codMunicipio' => '03-01', 'nombreMunicipio' => 'Chalatenango', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-02', 'nombreMunicipio' => 'Agua Caliente', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-03', 'nombreMunicipio' => 'Arcatao', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-04', 'nombreMunicipio' => 'Azacualpa', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-05', 'nombreMunicipio' => 'Cancasque', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-06', 'nombreMunicipio' => 'Citalá', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-07', 'nombreMunicipio' => 'Comalapa', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-08', 'nombreMunicipio' => 'Concepción Quezaltepeque', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-09', 'nombreMunicipio' => 'Dulce Nombre de María', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-10', 'nombreMunicipio' => 'El Carrizal', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-11', 'nombreMunicipio' => 'El Paraíso', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-12', 'nombreMunicipio' => 'La Laguna', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-13', 'nombreMunicipio' => 'La Palma', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-14', 'nombreMunicipio' => 'La Reina', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-15', 'nombreMunicipio' => 'Las Vueltas', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-16', 'nombreMunicipio' => 'Nombre de Jesús', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-17', 'nombreMunicipio' => 'Nueva Concepción', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-18', 'nombreMunicipio' => 'Nueva Trinidad', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-19', 'nombreMunicipio' => 'Ojos de Agua', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-20', 'nombreMunicipio' => 'Potonico', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-21', 'nombreMunicipio' => 'San Antonio de la Cruz', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-22', 'nombreMunicipio' => 'San Antonio los Ranchos', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-23', 'nombreMunicipio' => 'San Fernando', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-24', 'nombreMunicipio' => 'San Francisco Lempa', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-25', 'nombreMunicipio' => 'San Francisco Morazán', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-26', 'nombreMunicipio' => 'San Ignacio', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-27', 'nombreMunicipio' => 'San Isidro Labrador', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-28', 'nombreMunicipio' => 'San Luis del Carmen', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-29', 'nombreMunicipio' => 'San Miguel de Mercedes', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-30', 'nombreMunicipio' => 'San Rafael', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-31', 'nombreMunicipio' => 'Santa Rita', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-32', 'nombreMunicipio' => 'Tejutla', 'codDepartamento' => '03']);
        Municipios::create(['codMunicipio' => '03-33', 'nombreMunicipio' => 'Las Flores', 'codDepartamento' => '03']);

        Municipios::create(['codMunicipio' => '04-01', 'nombreMunicipio' => 'Cojutepeque', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-02', 'nombreMunicipio' => 'Candelaria', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-03', 'nombreMunicipio' => 'El Carmen', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-04', 'nombreMunicipio' => 'El Rosario', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-05', 'nombreMunicipio' => 'Monte San Juan', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-06', 'nombreMunicipio' => 'Oratorio de Concepción', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-07', 'nombreMunicipio' => 'San Bartolomé Perulapía', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-08', 'nombreMunicipio' => 'San Cristóbal', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-09', 'nombreMunicipio' => 'San José Guayabal', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-10', 'nombreMunicipio' => 'San Pedro Perulapán', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-11', 'nombreMunicipio' => 'San Rafael Cedros', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-12', 'nombreMunicipio' => 'San Ramón', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-13', 'nombreMunicipio' => 'Santa Cruz Analquito', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-14', 'nombreMunicipio' => 'Santa Cruz Michapa', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-15', 'nombreMunicipio' => 'Suchitoto', 'codDepartamento' => '04']);
        Municipios::create(['codMunicipio' => '04-16', 'nombreMunicipio' => 'Tenancingo', 'codDepartamento' => '04']);

        Municipios::create(['codMunicipio' => '05-01', 'nombreMunicipio' => 'Santa Tecla', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-02', 'nombreMunicipio' => 'Antiguo Cuscatlán', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-03', 'nombreMunicipio' => 'Colón', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-04', 'nombreMunicipio' => 'Huizúcar', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-05', 'nombreMunicipio' => 'Jayaque', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-06', 'nombreMunicipio' => 'Jicalapa', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-07', 'nombreMunicipio' => 'La Libertad', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-08', 'nombreMunicipio' => 'Nuevo Cuscatlán', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-09', 'nombreMunicipio' => 'San Juan Opico', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-10', 'nombreMunicipio' => 'Quezaltepeque', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-11', 'nombreMunicipio' => 'Sacacoyo', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-12', 'nombreMunicipio' => 'San José Villanueva', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-13', 'nombreMunicipio' => 'San Matías', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-14', 'nombreMunicipio' => 'San Pablo Tacachico', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-15', 'nombreMunicipio' => 'Talnique', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-16', 'nombreMunicipio' => 'Tamanique', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-17', 'nombreMunicipio' => 'Teotepeque', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-18', 'nombreMunicipio' => 'Tepecoyo', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-19', 'nombreMunicipio' => 'Zaragoza', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-20', 'nombreMunicipio' => 'Chiltuipán', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-21', 'nombreMunicipio' => 'Ciudad Arce', 'codDepartamento' => '05']);
        Municipios::create(['codMunicipio' => '05-22', 'nombreMunicipio' => 'Comasagua', 'codDepartamento' => '05']);

        Municipios::create(['codMunicipio' => '06-01', 'nombreMunicipio' => 'Zacatecoluca', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-02', 'nombreMunicipio' => 'San Juan Talpa', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-03', 'nombreMunicipio' => 'San Pedro Masahuat', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-04', 'nombreMunicipio' => 'San Juan Nonualco', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-05', 'nombreMunicipio' => 'Santiago Nonualco', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-06', 'nombreMunicipio' => 'Tapalhuaca', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-07', 'nombreMunicipio' => 'San Rafael Obrajuelo', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-08', 'nombreMunicipio' => 'San Emigdio', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-09', 'nombreMunicipio' => 'Santa María Ostuma', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-10', 'nombreMunicipio' => 'San Miguel Tepezontes', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-11', 'nombreMunicipio' => 'Mercedes La Ceiba', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-12', 'nombreMunicipio' => 'Olocuilta', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-13', 'nombreMunicipio' => 'Cuyultitán', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-14', 'nombreMunicipio' => 'San Pedro Nonualco', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-15', 'nombreMunicipio' => 'Santa Cruz Analquito', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-16', 'nombreMunicipio' => 'San Antonio Masahuat', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-17', 'nombreMunicipio' => 'San Luis La Herradura', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-18', 'nombreMunicipio' => 'Paraiso de Osorio', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-19', 'nombreMunicipio' => 'La Paz', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-20', 'nombreMunicipio' => 'El Rosario', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-21', 'nombreMunicipio' => 'Jerusalén', 'codDepartamento' => '06']);
        Municipios::create(['codMunicipio' => '06-22', 'nombreMunicipio' => 'San Juan Tepezontes', 'codDepartamento' => '06']);

        Municipios::create(['codMunicipio' => '07-01', 'nombreMunicipio' => 'La Unión', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-02', 'nombreMunicipio' => 'Anamorós', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-03', 'nombreMunicipio' => 'Bolívar', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-04', 'nombreMunicipio' => 'Concepción de Oriente', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-05', 'nombreMunicipio' => 'Conchagua', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-06', 'nombreMunicipio' => 'El Carmen', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-07', 'nombreMunicipio' => 'El Sauce', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-08', 'nombreMunicipio' => 'Intipucá', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-09', 'nombreMunicipio' => 'Lislique', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-10', 'nombreMunicipio' => 'Meanguera del Golfo', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-11', 'nombreMunicipio' => 'Nueva Esparta', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-12', 'nombreMunicipio' => 'Pasaquina', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-13', 'nombreMunicipio' => 'Polorós', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-14', 'nombreMunicipio' => 'San Alejo', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-15', 'nombreMunicipio' => 'San José', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-16', 'nombreMunicipio' => 'Santa Rosa de Lima', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-17', 'nombreMunicipio' => 'Yayantique', 'codDepartamento' => '07']);
        Municipios::create(['codMunicipio' => '07-18', 'nombreMunicipio' => 'Yucuaiquín', 'codDepartamento' => '07']);

        Municipios::create(['codMunicipio' => '08-01', 'nombreMunicipio' => 'San Francisco Gotera', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-02', 'nombreMunicipio' => 'Arambala', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-03', 'nombreMunicipio' => 'Cacaopera', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-04', 'nombreMunicipio' => 'Chilanga', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-05', 'nombreMunicipio' => 'Corinto', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-06', 'nombreMunicipio' => 'Delicias de Concepción', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-07', 'nombreMunicipio' => 'El Divisadero', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-08', 'nombreMunicipio' => 'El Rosario', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-09', 'nombreMunicipio' => 'Gualococti', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-10', 'nombreMunicipio' => 'Guatajiagua', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-11', 'nombreMunicipio' => 'Joateca', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-12', 'nombreMunicipio' => 'Jocoaitique', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-13', 'nombreMunicipio' => 'Meanguera', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-14', 'nombreMunicipio' => 'Osicala', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-15', 'nombreMunicipio' => 'Perquín', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-16', 'nombreMunicipio' => 'San Carlos', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-17', 'nombreMunicipio' => 'San Fernando', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-18', 'nombreMunicipio' => 'San Isidro', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-19', 'nombreMunicipio' => 'San Simón', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-20', 'nombreMunicipio' => 'Sensembra', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-21', 'nombreMunicipio' => 'Sociedad', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-22', 'nombreMunicipio' => 'Torola', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-23', 'nombreMunicipio' => 'Yamabal', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-24', 'nombreMunicipio' => 'Jocoro', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-25', 'nombreMunicipio' => 'Lolotiquillo', 'codDepartamento' => '08']);
        Municipios::create(['codMunicipio' => '08-26', 'nombreMunicipio' => 'Yoloaiquín', 'codDepartamento' => '08']);

        Municipios::create(['codMunicipio' => '09-01', 'nombreMunicipio' => 'San Miguel', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-02', 'nombreMunicipio' => 'Carolina', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-03', 'nombreMunicipio' => 'Chapeltique', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-04', 'nombreMunicipio' => 'Chinameca', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-05', 'nombreMunicipio' => 'Chirilagua', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-06', 'nombreMunicipio' => 'Ciudad Barrios', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-07', 'nombreMunicipio' => 'Comacarán', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-08', 'nombreMunicipio' => 'El Tránsito', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-09', 'nombreMunicipio' => 'Lolotique', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-10', 'nombreMunicipio' => 'Moncagua', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-11', 'nombreMunicipio' => 'Nueva Guadalupe', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-12', 'nombreMunicipio' => 'Nuevo Edén de San Juan', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-13', 'nombreMunicipio' => 'Quelepa', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-14', 'nombreMunicipio' => 'San Antonio del Mosco', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-15', 'nombreMunicipio' => 'San Gerardo', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-16', 'nombreMunicipio' => 'San Jorge', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-17', 'nombreMunicipio' => 'San Luis de la Reina', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-18', 'nombreMunicipio' => 'San Rafael Oriente', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-19', 'nombreMunicipio' => 'Sesori', 'codDepartamento' => '09']);
        Municipios::create(['codMunicipio' => '09-20', 'nombreMunicipio' => 'Uluazapa', 'codDepartamento' => '09']);

        Municipios::create(['codMunicipio' => '10-01', 'nombreMunicipio' => 'San Salvador', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-02', 'nombreMunicipio' => 'Aguilares', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-03', 'nombreMunicipio' => 'Apopa', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-04', 'nombreMunicipio' => 'Ayutuxtepeque', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-05', 'nombreMunicipio' => 'Cuscatancingo', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-06', 'nombreMunicipio' => 'Ciudad Delgado', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-07', 'nombreMunicipio' => 'El Paisnal', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-08', 'nombreMunicipio' => 'Guazapa', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-09', 'nombreMunicipio' => 'Ilopango', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-10', 'nombreMunicipio' => 'Mejicanos', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-11', 'nombreMunicipio' => 'Nejapa', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-12', 'nombreMunicipio' => 'Panchimalco', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-13', 'nombreMunicipio' => 'Rosario de Mora', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-14', 'nombreMunicipio' => 'San Marcos', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-15', 'nombreMunicipio' => 'San Martín', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-16', 'nombreMunicipio' => 'Santiago Texacuangos', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-17', 'nombreMunicipio' => 'Santo Tomás', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-18', 'nombreMunicipio' => 'Soyapango', 'codDepartamento' => '10']);
        Municipios::create(['codMunicipio' => '10-19', 'nombreMunicipio' => 'Tonacatepeque', 'codDepartamento' => '10']);

        Municipios::create(['codMunicipio' => '11-01', 'nombreMunicipio' => 'San Vicente', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-02', 'nombreMunicipio' => 'Apastepeque', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-03', 'nombreMunicipio' => 'Guadalupe', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-04', 'nombreMunicipio' => 'San Cayetano Istepeque', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-05', 'nombreMunicipio' => 'San Esteban Catarina', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-06', 'nombreMunicipio' => 'San Ildefonso', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-07', 'nombreMunicipio' => 'San Lorenzo', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-08', 'nombreMunicipio' => 'San Sebastián', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-09', 'nombreMunicipio' => 'Santa Clara', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-10', 'nombreMunicipio' => 'Santo Domingo', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-11', 'nombreMunicipio' => 'Tecoluca', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-12', 'nombreMunicipio' => 'Tepetitán', 'codDepartamento' => '11']);
        Municipios::create(['codMunicipio' => '11-13', 'nombreMunicipio' => 'Verapaz', 'codDepartamento' => '11']);

        Municipios::create(['codMunicipio' => '12-01', 'nombreMunicipio' => 'Santa Ana', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-02', 'nombreMunicipio' => 'Candelaria de la Frontera', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-03', 'nombreMunicipio' => 'Chalchuapa', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-04', 'nombreMunicipio' => 'Coatepeque', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-05', 'nombreMunicipio' => 'El Congo', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-06', 'nombreMunicipio' => 'El Porvenir', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-07', 'nombreMunicipio' => 'Masahuat', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-08', 'nombreMunicipio' => 'Metapán', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-09', 'nombreMunicipio' => 'San Antonio Pajonal', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-10', 'nombreMunicipio' => 'San Sebastián Salitrillo', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-11', 'nombreMunicipio' => 'Santa Rosa Guachipilín', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-12', 'nombreMunicipio' => 'Santiago de la Frontera', 'codDepartamento' => '12']);
        Municipios::create(['codMunicipio' => '12-13', 'nombreMunicipio' => 'Texistepeque', 'codDepartamento' => '12']);

        Municipios::create(['codMunicipio' => '13-01', 'nombreMunicipio' => 'Sonsonate', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-02', 'nombreMunicipio' => 'Acajutla', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-03', 'nombreMunicipio' => 'Armenia', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-04', 'nombreMunicipio' => 'Caluco', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-05', 'nombreMunicipio' => 'Cuisnahuat', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-06', 'nombreMunicipio' => 'Izalco', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-07', 'nombreMunicipio' => 'Juayúa', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-08', 'nombreMunicipio' => 'Nahuizalco', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-09', 'nombreMunicipio' => 'Nahulingo', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-10', 'nombreMunicipio' => 'Salcoatitán', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-11', 'nombreMunicipio' => 'San Antonio del Monte', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-12', 'nombreMunicipio' => 'San Julián', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-13', 'nombreMunicipio' => 'Santa Catarina Masahuat', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-14', 'nombreMunicipio' => 'Santa Isabel Ishuatán', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-15', 'nombreMunicipio' => 'Santo Domingo de Guzmán', 'codDepartamento' => '13']);
        Municipios::create(['codMunicipio' => '13-16', 'nombreMunicipio' => 'Sonzacate', 'codDepartamento' => '13']);

        Municipios::create(['codMunicipio' => '14-01', 'nombreMunicipio' => 'Usulután', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-02', 'nombreMunicipio' => 'Alegría', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-03', 'nombreMunicipio' => 'Berlín', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-04', 'nombreMunicipio' => 'California', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-05', 'nombreMunicipio' => 'Concepción Batres', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-06', 'nombreMunicipio' => 'El Triunfo', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-07', 'nombreMunicipio' => 'Ereguayquín', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-08', 'nombreMunicipio' => 'Estanzuelas', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-09', 'nombreMunicipio' => 'Jiquilisco', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-10', 'nombreMunicipio' => 'Jucuarán', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-11', 'nombreMunicipio' => 'Ozatlán', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-12', 'nombreMunicipio' => 'Puerto El Triunfo', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-13', 'nombreMunicipio' => 'San Agustín', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-14', 'nombreMunicipio' => 'San Buenaventura', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-15', 'nombreMunicipio' => 'San Dionisio', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-16', 'nombreMunicipio' => 'San Francisco Javier', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-17', 'nombreMunicipio' => 'Santa Elena', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-18', 'nombreMunicipio' => 'Santa María', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-19', 'nombreMunicipio' => 'Santiago de María', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-20', 'nombreMunicipio' => 'Tecapán', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-21', 'nombreMunicipio' => 'Jucuapa', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-22', 'nombreMunicipio' => 'Mercedes Umaña', 'codDepartamento' => '14']);
        Municipios::create(['codMunicipio' => '14-23', 'nombreMunicipio' => 'Nueva Granada', 'codDepartamento' => '14']);

    }
}
